### ISSUE TITLE
the bird is cute keep it on the header

### ISSUE THREAD

**Issue by Spentine** [Doduodrio/doduodrio.github.io#1]
![image](https://github.com/Doduodrio/doduodrio.github.io/assets/114318049/15d7cf31-82f8-4879-9ca3-ebebf7bd7a01)
the bird is cute

**Comment by Doduodrio** [comment]
I was thinking about redesigning the site to be simpler but we shall see

**Comment by Spentine** [comment]
did u do it yet

**Comment by Doduodrio** [comment]
Not yet...

**Comment by Spentine** [comment]
😭

**Comment by Spentine** [comment]
pls do it 🥺

**Comment by Doduodrio** [comment]
Don't worry it's still on the website, just on the art page. I don't plan to change the website icon.

**Comment by Spentine** [comment]
This thread is 4 months old
